path.begin();
path.addarc(0,360, 95,95);
path.fill();

path.draw(@@outlinePenColor);

transform.reset();
transform.rotate(0);
brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addlines(0,-42, 10,0, -10,0);
path.close();
path.fill();
path.draw();
brush.color("#000");
gradientbrush.color("#000");
path.begin();
path.addlines(0,-42, -10,0, 0,0);
path.close();
path.fill();

transform.reset();
transform.rotate(90);
brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addlines(0,-42, 10,0, -10,0);
path.close();
path.fill();
path.draw();
brush.color("#000");
gradientbrush.color("#000");
path.begin();
path.addlines(0,-42, -10,0, 0,0);
path.close();
path.fill();

transform.reset();
transform.rotate(180);
brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addlines(0,-42, 10,0, -10,0);
path.close();
path.fill();
path.draw();
brush.color("#000");
gradientbrush.color("#000");
path.begin();
path.addlines(0,-42, -10,0, 0,0);
path.close();
path.fill();

transform.reset();
transform.rotate(270);
brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addlines(0,-42, 10,0, -10,0);
path.close();
path.fill();
path.draw();
brush.color("#000");
gradientbrush.color("#000");
path.begin();
path.addlines(0,-42, -10,0, 0,0);
path.close();
path.fill();

transform.reset();
transform.rotate(45);
brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addlines(0,-35, 7,0, -7,0);
path.close();
path.fill();
path.draw();
brush.color("#000");
gradientbrush.color("#000");
path.begin();
path.addlines(0,-35, -7,0, 0,0);
path.close();
path.fill();

transform.reset();
transform.rotate(135);
brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addlines(0,-35, 7,0, -7,0);
path.close();
path.fill();
path.draw();
brush.color("#000");
gradientbrush.color("#000");
path.begin();
path.addlines(0,-35, -7,0, 0,0);
path.close();
path.fill();

transform.reset();
transform.rotate(225);
brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addlines(0,-35, 7,0, -7,0);
path.close();
path.fill();
path.draw();
brush.color("#000");
gradientbrush.color("#000");
path.begin();
path.addlines(0,-35, -7,0, 0,0);
path.close();
path.fill();

transform.reset();
transform.rotate(315);
brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addlines(0,-35, 7,0, -7,0);
path.close();
path.fill();
path.draw();
brush.color("#000");
gradientbrush.color("#000");
path.begin();
path.addlines(0,-35, -7,0, 0,0);
path.close();
path.fill();

brush.color("#fff");
gradientbrush.color("#fff");
path.begin();
path.addarc(0,360, 20,20);
path.fill();
path.draw();
