<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SketchPen.Plot.Drawing\SketchPen.Plot.Drawing.csproj" />
    <ProjectReference Include="..\SketchPen.Plot.Skia\SketchPen.Plot.Skia.csproj" />
    <ProjectReference Include="..\SketchPen.Plot\SketchPen.Plot.csproj" />
  </ItemGroup>

</Project>
